config/routes.rb
Rails.application.routes.draw do



  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end
  root to: "welcome#index"
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  default_scope {order('created_at DESC')}
#  private

#  def name=(s)
#    write_attribute(:name, s.to_s.titleize)
#  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    user_path resource.id
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @user = current_user
    @item = @user.items.new(item_params)
    @new_item = Item.new

    if @item.save
      flash[:notice] = "Your item was saved correctly"
    else
      flash[:error] = "oops, something didn't work there."
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  def destroy
    @user = current_user
    @item = @user.items.find(params[:id])

    if @item.destroy
      flash[:notice] = "Done!"
    else
      flash[:error] = "woops, try again"
    end

    respond_to do |format|
       format.html
       format.js
     end

  end


  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    skip_before_action :authenticate_user!, only: :index

    def index
    end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include ActionView::Helpers::DateHelper


  def days_left(item)
    distance_of_time_in_words(item.created_at, Date.today - 6.days)
  end

end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item], remote: true do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter Task" %>
    </div>
      <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>

app/views/items/_item.html.erb
<%= content_tag :div, class: 'media', id: "item-#{item.id}" do %>
    <div class="delete-item col-lg-1">
        <%= link_to "", user_item_path({user_id: @user.id, id: item.id}), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
    </div>
    <li class="list-group-item col-lg-11">
        <div class="created-at-time badge col-lg-3">
            <%= days_left(item) %> left
        </div>

        <div class="item-name col-lg-2">
            <%= item.name %>
        </div>
    </li>
<% end %>

app/views/items/create.js.erb
$('.js-items').prepend("<%= escape_javascript(render partial: 'items/item', locals: {item: @item}) %>");
$('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: {user: @user, item: @new_item}) %>");
$('.js-items-count').html("<%= pluralize(@item.user.items.count, 'task') %> left");

app/views/items/destroy.js.erb
$('#item-' +<%= @item.id %>).hide();
$('.js-items-count').html("<%= pluralize(@item.user.items.count, 'task') %> left");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
    <body>
      <header class="navbar navbar-fixed-top navbar-inverse navbar-custom">
        <div class="container">
          <div class="nav-title">
          <% if user_signed_in? %>
            Signed in as: <strong><%= current_user.email %></strong>
          </div>
          <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Task List', user_path(current_user), :class => 'navbar-link' %></li>
            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
          </ul>
            <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %></li>
            <li><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %></li>
          </ul>
        </nav>
        <% end %>
        </div>
      </header>
          <%= yield %>
    </body>

    </html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="media">
      <br />

      <div class="media-body">
        <h2 class="media-heading"><%= @user.first_name %> <%= @user.last_name %></h2>
        <br>

        <h3><div class='js-items-count'><%= pluralize(@user.items.count, 'task') %> left </div></h3>
        <br>

        <div class="new-item">
          <%= render partial: "items/form", locals: {user: @user, item: Item.new} %>
        </div>
      </div>
      <br>

        <div class="media js-items">
          <ul class="list-group">
            <% @user.items.each do |item| %>
            <%= render partial: 'items/item', locals: {user: @user, item: item} %>
            <% end %>
          </ul>
        </div>

    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<header>
  <div class="lander">
    <div class="lander-text">
    <p>Blocitoff</p>
    <%= link_to "Get Started!", new_user_registration_path, class: "btn btn-success" %>
    <p>A place to organize your life.</p>
  </div>
</header>